import './globals.css'
import { ClerkProvider } from '@clerk/nextjs/app-beta'
import { Inter } from 'next/font/google'
export const metadata = {
	title: 'Welcome to Noxy - dream!',
	description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body className={` ${inter.className} bg-[#fafaf9]	 antialiased`}>{children}</body>
			</ClerkProvider>
		</html>
	)
}
